# Generated by Django 3.0.7 on 2020-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_published',
            field=models.BooleanField(default=True),
        ),
    ]
