# Generated by Django 3.0.7 on 2020-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
