# Generated by Django 3.0.7 on 2020-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_show_in_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
