# Generated by Django 3.0.7 on 2020-06-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_post_show_in_navbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_order']},
        ),
    ]
