# Generated by Django 3.0.7 on 2020-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('slug', models.SlugField()),
                ('page_order', models.PositiveSmallIntegerField()),
                ('page_show_in_navbar', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_show_in_navbar',
        ),
    ]
