# Generated by Django 3.0.7 on 2020-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200625_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='post_content',
            new_name='page_content',
        ),
        migrations.AlterField(
            model_name='page',
            name='page_show_in_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
