# Generated by Django 3.0.7 on 2020-06-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200625_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='kat'),
            preserve_default=False,
        ),
    ]
