# Generated by Django 3.0.7 on 2020-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
