# Generated by Django 3.0.7 on 2020-06-26 16:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200626_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_order',
            field=models.PositiveSmallIntegerField(default=blog.models.defaultOrder),
        ),
    ]
