# Generated by Django 3.0.7 on 2020-07-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200626_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caegory_order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
