# Generated by Django 3.0.7 on 2020-07-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_caegory_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='caegory_order',
            new_name='category_order',
        ),
    ]
