# Generated by Django 3.0.7 on 2020-07-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200703_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_order']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_order']},
        ),
    ]
